### ISSUE TITLE
Can't run it. Failed to get max frame.

### ISSUE THREAD

**Issue by sbinnee** [jasonjmcghee/xrem#3]
Hi. I came across your project on HN a while ago. It's nice that you created rem without xcode+swift because I do not want to go through apple signing process. I really appreciate this repo.

While trying to run xrem, I met this error message. I am a noob to rust and svelte. I suspect that it failed to get a max frame from sqlite database. 

```sh
% npm run tauri dev -- --release
(...)
warning: `xrem` (bin "xrem") generated 22 warnings (run `cargo fix --bin "xrem"` to apply 3 suggestions)
    Finished release [optimized] target(s) in 6.07s
starting app...
starting server...
started server...
9:36:06 AM [vite-plugin-svelte] /Users/noris/workspace/xrem/src/routes/search/ThumbnailCard.svelte:24:0 A11y: visible, non-interactive elements with an on:click event must be accompanied by a keyboard event handler. Consider whether an interactive element such as <button type="button"> or <a> might be more appropriate. See https://svelte.dev/docs/accessibility-warnings#a11y-click-events-have-key-events for more details.
9:36:06 AM [vite-plugin-svelte] /Users/noris/workspace/xrem/src/routes/search/ThumbnailCard.svelte:24:0 A11y: <div> with click handler must have an ARIA role
9:36:06 AM [vite-plugin-svelte] /Users/noris/workspace/xrem/src/routes/search/ThumbnailCard.svelte:70:4 Unused CSS selector ".thumbnail-card .app-name"
9:36:06 AM [vite-plugin-svelte] /Users/noris/workspace/xrem/src/routes/search/ThumbnailCard.svelte:82:4 Unused CSS selector ".thumbnail-card .app-name"
thread 'tokio-runtime-worker' panicked at src/server.rs:93:14:
Failed to get max frame: InvalidColumnType(0, "MAX(id)", Null)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/server.rs:88:48:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/server.rs:88:48:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```
I believe that it refers to `async fn get_max_frame_handler()` in `src-tauri/src/server.rs`. 

(Don't know if it helps) I am running 
- Vertura on M2 mac
- rustc 1.76.0

**Comment by energyGiver** [comment]
interested in this project, but same error. M1 Sonoma.

thread 'tokio-runtime-worker' panicked at src/server.rs:93:14:
Failed to get max frame: InvalidColumnType(0, "MAX(id)", Null)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at src/server.rs:88:48:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/server.rs:88:48:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }

**Comment by jasonjmcghee** [comment]
Probably has to do with first execution / empty sqlite db - taking a quick look...
